### PR TITLE
adjustments for latest version of SLURM

### PR DESCRIPTION
**Pull request by rmodrak**
Hi James,  This problem resulted from a change in starting index for certain SLURM environment variables.  The latest pull request address this issue, I believe in a way that works for both old and new versions of SLURM.

On Thu, Sep 21, 2017 at 4:50 PM, R Modrak <rmodrak@gmail.com> wrote:

    Thanks for pointing this out.  I'm working on a fix now...

    On Mon, Sep 18, 2017 at 6:50 AM, James A. Smith <jas11@princeton.edu> wrote:

        Hi Ryan,

        I have seisflows working with tigergpu_sm, but the taskid issue I brought up previously is an issue still and now affects tiger. If you run the Checkers3D example on tiger you should see that the index out of range error is happening because of the taskid.

        Anyway, it's not that important for me right now since I'm using the gpu small.

        James

### CODE REVIEW

**Comment by jas11** [comment]
Thanks, Ryan. I tried your fix and I still get the same error. I ran it using the devel version of seisflows. Let me know if I can help you with any more tests.

IOError: [Errno 2] No such file or directory:

Traceback (most recent call last):
  File "/var/spool/slurmd/job3660559/slurm_script", line 41, in <module>
    func(**kwargs)
  File "/tigress/jas11/packages/seisflows/seisflows/solver/specfem3d.py", line 106, in eval_func
    super(specfem3d, self).eval_func(*args, **kwargs)
  File "/tigress/jas11/packages/seisflows/seisflows/solver/base.py", line 193, in eval_func
    unix.cd(self.cwd)
  File "/tigress/jas11/packages/seisflows/seisflows/solver/base.py", line 585, in cwd
    return join(PATH.SOLVER, self.source_name)
  File "/tigress/jas11/packages/seisflows/seisflows/solver/base.py", line 580, in source_name
    return self.source_names[self.taskid]
IndexError: list index out of range

________________________________

**Comment by jas11** [comment]
Nevermind, I checked it and it worked for 2 sources. One source is not finishing this evening but it may just be the cluster.

James

________________________________
From: James A. Smith
Sent: Sunday, September 24, 2017 8:39 PM
To: rmodrak/seisflows
Subject: RE: [rmodrak/seisflows] adjustments for latest version of SLURM (#78)

Thanks, Ryan. I tried your fix and I still get the same error. I ran it using the devel version of seisflows. Let me know if I can help you with any more tests.

IOError: [Errno 2] No such file or directory:

Traceback (most recent call last):
  File "/var/spool/slurmd/job3660559/slurm_script", line 41, in <module>
    func(**kwargs)
  File "/tigress/jas11/packages/seisflows/seisflows/solver/specfem3d.py", line 106, in eval_func
    super(specfem3d, self).eval_func(*args, **kwargs)
  File "/tigress/jas11/packages/seisflows/seisflows/solver/base.py", line 193, in eval_func
    unix.cd(self.cwd)
  File "/tigress/jas11/packages/seisflows/seisflows/solver/base.py", line 585, in cwd
    return join(PATH.SOLVER, self.source_name)
  File "/tigress/jas11/packages/seisflows/seisflows/solver/base.py", line 580, in source_name
    return self.source_names[self.taskid]
IndexError: list index out of range

________________________________

**Comment by rmodrak** [comment]
Hi James,

Thanks very much for your help testing.

Just tried two tests on tiger-- 1 source and 2 sources.  Both appeared to
pass.  I'll go ahead and accept the pull request.  Feel free to respond
back if there are future problems.

Ryan

**Comment by katigeophysics** [comment]
Dear Dr Ryan,

I am trying to run the examples 2D at seisflow and i am not able to run. 

My tests are sucesfuly done and i realise that woulb be impossible to run since the file legacy,py it is not at the package for download. 

Also i found other package at  https://github.com/DmBorisov/SeisFlows_tunnel but it is also not working to run this examples.

Could you please help me? 

I am very interest to use seisflow, thank you very much for your time.

**Comment by rmodrak** [comment]
Hi Kati,

Please see the following newly created issue:
#81

Thanks,
Ryan

**Pull request merged**
